### ISSUE TITLE
Unknown system error -1 when protoc-gen-ada is run

### ISSUE THREAD

**Issue by TheMightyDuckOfDoom** [persan/protobuf-ada#1]
I'd like to use protobuffers in Ada. I got it as far as to the unit tests, but when I run protoc-gen-ada I get an unknown system error -1.

> terminate called after throwing an instance of 'std::system_error'
  what():  Unknown error -1
  Aborted (core dumped)

Additionaly there where many changes I had to do in order to get it to compile:

- [ ] Changed `$(shell which gps)` to `$(shell which gnat-gps)`
- [ ] Added `using namespace std;` to the headers which use `vector`, `map`, `set`
- [ ] Included libboost where needed, for `scoped_ptr` and 'scoped_array' -> I read that these were included in protobuf 3.5.0 but not anymore.
- [ ] Had to remove in google-protobuf.gpr:  `"Makefile", "project file","MarkDown","Text"`
- [ ] Downloaded and installed aunit

It would be nice to know which versions of protobuf and protoc you are using and how it is that you don't need 'std::' before 'vector' and so on :smile:
I'm using GNAT Cummunity 2018 and libprotoc 3.6.1.

**Comment by mgrojo** [comment]
Hi @TheMightyDuckOfDoom. Did you get to something? I was able to get as far as you, following some of your instructions and using the last commit (a75665463795179511a116135decd761b2181f0e) (additionally I had to create `compiler/protoc_ada.gpr` from `compiler/protoc_ada.gpr.in`). Then I got the same abort as you, I installed the debug version of libprotobuf and debugged it getting this backtrace:

```gdb
#0  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:50
#1  0x00007ffff766f859 in __GI_abort () at abort.c:79
#2  0x00007ffff78f8911 in ?? () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#3  0x00007ffff790438c in ?? () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#4  0x00007ffff79043f7 in std::terminate() () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#5  0x00007ffff79046a9 in __cxa_throw () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#6  0x00007ffff78fb73f in std::__throw_system_error(int) () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#7  0x00007ffff7b4eb8f in std::call_once<void (&)()> (__once=..., __f=<optimised out>) at /usr/include/x86_64-linux-gnu/c++/9/bits/gthr-default.h:700
#8  0x00007ffff7fe0b8a in call_init (l=<optimised out>, argc=argc@entry=1, argv=argv@entry=0x7fffffffdc58, env=env@entry=0x7fffffffdc68) at dl-init.c:72
#9  0x00007ffff7fe0c91 in call_init (env=0x7fffffffdc68, argv=0x7fffffffdc58, argc=1, l=<optimised out>) at dl-init.c:30
#10 _dl_init (main_map=0x7ffff7ffe190, argc=1, argv=0x7fffffffdc58, env=0x7fffffffdc68) at dl-init.c:119
#11 0x00007ffff7fd013a in _dl_start_user () from /lib64/ld-linux-x86-64.so.2
#12 0x0000000000000001 in ?? ()
#13 0x00007fffffffe021 in ?? ()
#14 0x0000000000000000 in ?? ()
```
Lines in dl-init.c might match this version: https://github.com/lattera/glibc/blob/master/elf/dl-init.c

Something related to the loading of the library, but beyond my knowledge. Any ideas?

Hi @persan, is this still used at your side?

**Comment by mgrojo** [comment]
I pushed the changes to my fork, in case someone wants to carry on from there.
https://github.com/mgrojo/protobuf-ada/commit/644b39436157c42d4b0da3b4781381c1221ff958

**Comment by mgrojo** [comment]
Good news! I was able to fix it and now all tests are passing. I made the corresponding pull request.
